### PR TITLE
Add META-INF/services

### LINKED ISSUE #96: DefaultTracer resolves to NullTracer when HttpZipkinTracer is on the classpath
## Describe the Bug
Scala 2.13.5
zipkin-finagle-http_2.13 2.2.4

`DefaultTracer` resolves to `NullTracer` when `HttpZipkinTracer` is on the classpath.

## Steps to Reproduce
I didn't manage to write a failing test because the project failed to build. 
So here's the simplest reproducer.  https://github.com/notxcain/zipkin-http-repro
Just run `sbt run`.

## Expected Behaviour
`DefaultTracer` resolves to `HttpZipkinTracer`

### PR DESCRIPTION
**Pull request by notxcain**
I think that should resolve #96

### CODE REVIEW

**Comment by notxcain** [comment]
CI fails because of license header check. I've added `META-INF` to the exclude list but no luck.

**Comment by crispywalrus** [comment]
@notxcain 
This is the first release of the year for zipkin-finagle and that causes a problem the fix for which is described [here](https://github.com/openzipkin/zipkin-finagle/blob/master/RELEASE.md#first-release-of-the-year)

**Comment by notxcain** [comment]
@crispywalrus done!

**Comment by crispywalrus** [comment]
looks great! thanks @notxcain

**Comment by jcchavezs** [comment]
Thanks a lot @notxcain!

**Comment by notxcain** [comment]
Thank you folks!

**Pull request merged**
