### PR TITLE
Adds README and organizes flags

### PR DESCRIPTION
**Pull request by adriancole**
This organizes configuration flags into a namespace that seems more
simple, and more similar to other tracers like Sleuth and Brave.

Flag | Default | Description
--- | --- | ---
zipkin.initialSampleRate | 0.001 (0.1%) | Percentage of traces to sample (report to zipkin) in the range [0.0 - 1.0]
zipkin.kafka.bootstrapServers | localhost:9092 | Initial set of kafka servers to connect to, rest of cluster will be discovered (comma separated)
zipkin.kafka.topic | zipkin | Kafka topic zipkin traces will be sent to

Ex. Here's how to configure the Kafka server with a system property:
```bash
$ java -Dzipkin.kafka.bootstrapServers=192.168.99.100 ...
```

### CODE REVIEW

**Comment by adriancole** [comment]
calling on zipkin+finagle folks for a glance (not everyone needed, just someone besides me..
@kristofa @eirslett @sveinnfannar @mosesn @schrepfler @kevinoliver @klingerf 

so I think I need a second opinion on the flag names (just because I want to make sure future ones make sense similarly).

I've made a demo that uses the code on this branch https://github.com/openzipkin/zipkin-finagle-example

After we merge this, I can feel confident in improving and adding the http transport. Once that's in, we can cut a pre 1.0 release

**Comment by sveinnfannar** [comment]
Yes I makes sense to simplify the flags like this :thumbs up:

**Comment by adriancole** [comment]
thanks @sveinnfannar!

**Comment by mosesn** [comment]
LGTM, though belatedly

**Comment by adriancole** [comment]
thanks all the same!

**Pull request merged**
