### PR TITLE
Update to scala 2.12 and finagle 6.42.0

### PR DESCRIPTION
**Pull request by crispywalrus**
The license plugin fails for unknown reasons (unknown to me) Beyond that this seems to work properly. For #21

### CODE REVIEW

**Comment by adriancole** [comment]
try running `./mvnw com.mycila:license-maven-plugin:format` ?

**Comment by crispywalrus** [comment]
this https://github.com/openzipkin/zipkin-finagle/blob/master/kafka/pom.xml#L53 prevents me from making progress. there is not a version of this plugin supporting a 2.12 version of kafka. Upgrading would seem to be in order although that blocks progress until there is a 2.12 supporting version. I'm a bit concerned about the comment pinning the version of kafka at 0.8xxx. Is this a hard requirement for another component or is it here to force an older api version for compatibility reasons?

**Comment by adriancole** [comment]
old kafka was due to deployment reasons. this might be something we can change now...

https://groups.google.com/forum/#!searchin/zipkin-user/kafka%7Csort:relevance/zipkin-user/rQpecbvc6Y0/6aUVZKARAQAJ

@kristofa @mjbryant how's things with kafka your way?

Also, we can add a kafka09 or 10 variant upstream to zipkin-reporter and re-use it here. That's assuming one of those support 2.12...

**Comment by adriancole** [comment]
@crispywalrus which version of kafka do you run?

**Comment by adriancole** [comment]
actually, the minimum version for 2.12 is kafka 0.10.2, so this simplifies the discussion substantially :)

https://issues.apache.org/jira/browse/KAFKA-4376

**Comment by adriancole** [comment]
PS it appears the main problem here is that the test dependency is colliding with the classpath, not that production has a classpath conflict (ex kafka-clients has no scala dependency). What we should probably disable the test until there's a test container. Reason is, I fear that most are still using kafka 0.8+ brokers and we don't want to force all finagle users to upgrade their brokers just because a test setup issue.

**Comment by adriancole** [comment]
ok.. here's the idea.

keep kafka using old client, but change the test fixtures to use the 0.10.2+ broker at the same time we update to scala 2.12. Probably will work.

**Comment by crispywalrus** [comment]
👍 thanks @adriancole

**Pull request closed without merging**
