### PR TITLE
Zipkin tracer using Kafka as a transport

### PR DESCRIPTION
**Pull request by sveinnfannar**
See: https://github.com/twitter/finagle/pull/515

### CODE REVIEW

**Comment by eirslett** [comment]
Maybe we should use something else than Pants as the build tool?

**Comment by sveinnfannar** [comment]
@eirslett absolutely, I'm adding a proper sbt + travisci setup. Had to tangent to some internal Quizup work but I'll finish this tomorrow.

**Comment by eirslett** [comment]
If you go with Gradle, openzipkin has a couple of nice deployment scripts written by @abesto that let us sync automatically to maven/bintray. They are now hidden in the scala branch of zipkin.

**Comment by sveinnfannar** [comment]
Ok great, I'll make sure to check that out

**Comment by adriancole** [comment]
finagle 6.36 is out the door, which means we can now start work on this!

**Comment by adriancole** [comment]
I can help with this. I think I'll make this build only for scala 2.11 as it dramatically simplifies the machinery. We can let people who need 2.10 complain before we sink extra effort to cross-build/cross-deploy

**Pull request merged**
