### PR TITLE
Bumps to Finagle 7

### LINKED ISSUE #34: Publish zipkin-finagle built for finagle 7.0.0
Finagle 7 was released a few days ago but zipkin finagle doesn't have a build available for it.  It'd be nice to be able to publish a new artifact that was built against finagle 7

### PR DESCRIPTION
**Pull request by adriancole**
cc @devshorts @klingerf

Note, I'm bumping minor in case we need to release another 6.x release. I get a compile failure locally. help wanted!

Fixes #34

### CODE REVIEW

**Comment by devshorts** [comment]
Yeah interesting. I'm getting a 
```
[ERROR] /Users/devshorts/src/zipkin-finagle/core/src/main/java/zipkin/finagle/ReporterMetricsAdapter.java:[18,33] cannot access com.twitter.finagle.stats.StatsReceiver
  bad class file: /Users/devshorts/.m2/repository/com/twitter/util-stats_2.12/7.0.0/util-stats_2.12-7.0.0.jar(/com/twitter/finagle/stats/StatsReceiver.class)
    class file contains malformed variable arity method: addGauge$(com.twitter.finagle.stats.StatsReceiver,java.lang.String[],scala.Function0)
    Please remove or make sure it appears in the correct subdirectory of the classpath.
```
Error local.  I'm curious if this is some java/scala interop bug?

**Comment by klingerf** [comment]
I think we're running into an issue with twitter/finagle@fa91412d, which changed the method signatures on StatReceiver methods to accept a verbosity param. Am not sure offhand how to change this code to fix it, but I can dig around a bit.

**Comment by adriancole** [comment]
>
> I think we're running into an issue with twitter/finagle@fa91412
> <https://github.com/twitter/finagle/commit/fa91412d>, which changed the
> method signatures on StatReceiver methods to accept a verbosity param. Am
> not sure offhand how to change this code to fix it, but I can dig around a
> bit.
>
mind reporting back on any findings? cc @mosesn

**Comment by mosesn** [comment]
I think we're going to publish a fix soon–our java compilation tests didn't catch this one, sorry about that!

https://github.com/twitter/util/issues/200

**Comment by devshorts** [comment]
@mosesn thanks for the quick turnaround! You guys rock

**Comment by vkostyukov** [comment]
We'll be releasing 7.1 quite soon - you should upgrade to it directly (it will have a fix). Sorry for the troubles.

**Comment by adriancole** [comment]
ok looks like it is good now

**Comment by adriancole** [comment]
going out as v1.1.0

**Pull request merged**
