### PR TITLE
another month, another version of finagle

### PR DESCRIPTION
**Pull request by chris-vale-ck**
18.2.0!

### CODE REVIEW

**Comment by chris-vale-ck** [comment]
@adriancole could I get some eyes on this please

**Comment by adriancole** [comment]
was on chinese new year holiday!

@jcchavezs wanna do the merge and release honors? I'd like to stop being the person who has to do everything

**Comment by jcchavezs** [comment]
Doing in a couple of hours :). Existed to do it.

**Comment by chris-vale-ck** [comment]
Thanks for the prompt attention

**Pull request merged**
